# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20160526_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
